# test file (2^24 bytes, ASCII, START/END markers):
# { printf START; tr -dc 'A-Za-z0-9' < /dev/urandom | head -c 16777208; printf END; } > /var/www/html/f2p24b

user root;
worker_processes 1;
pid /run/nginx-origin.pid;
error_log /var/log/nginx-origin.error.log warn;

events {}

http {
    access_log off;
    sendfile on;

    default_type application/octet-stream;
    types {
        text/html html;
        video/mp4 mp4;
    }

    client_body_temp_path /var/lib/nginx-origin/body;
    proxy_temp_path /var/lib/nginx-origin/proxy;
    fastcgi_temp_path /var/lib/nginx-origin/fastcgi;
    uwsgi_temp_path /var/lib/nginx-origin/uwsgi;
    scgi_temp_path /var/lib/nginx-origin/scgi;

    server {
        listen 127.0.0.1:8080;
        listen 127.0.0.2:3333;
        listen 127.0.0.3:3333;
        listen 127.0.0.4:3333;
        server_name local_origin local_origin1 local_origin2 _;

        root /var/www/html;

        location / {
        }
    }
}
